import type { Lot, ScoredLot } from "./types";
import { scoreLot } from "./score";

/** Frozen close dates so SSR and the client never drift. Desk clock: 2026-08-31. */
const T = (isoDate: string) => `${isoDate}T17:00:00-05:00`;

export const MIDWEST: Lot[] = [
  {
    id: "hcs-26-1844",
    lane: "midwest",
    venue: "hennepin-sheriff",
    venueLabel: "Hennepin Sheriff",
    lotNo: "1844",
    title: "2016 Ford Explorer Interceptor — 148k, runs, clean title",
    category: "vehicle",
    city: "Minneapolis",
    state: "MN",
    miles: 8,
    endsAt: T("2026-09-03"),
    hammer: 2100,
    bidders: 7,
    titleStatus: "clean",
    flags: ["fleet-service", "spot-rust"],
    notes: "Hennepin marked unit. Light bar pulled. Rear cage still in. Title in the file.",
    comps: [
      { label: "FB Marketplace 2016 Interceptor 140k", price: 6200 },
      { label: "Craigslist Blaine 2015 160k", price: 4800 },
      { label: "Wholesale Manheim Minneapolis", price: 3900 },
    ],
    retail: 5400,
    imageHint: "white police explorer",
  },
  {
    id: "mpd-26-0912",
    lane: "midwest",
    venue: "minneapolis-pd",
    venueLabel: "Minneapolis PD",
    lotNo: "0912",
    title: "Seized iPhone 14 Pro lot (12 units) — iCloud locked",
    category: "phone",
    city: "Minneapolis",
    state: "MN",
    miles: 4,
    endsAt: T("2026-09-02"),
    hammer: 180,
    bidders: 11,
    titleStatus: "none",
    flags: ["locked", "icloud"],
    notes: "Every unit shows activation lock. Yard will not provide Apple release letters.",
    comps: [{ label: "Unlocked 14 Pro street", price: 420 }],
    retail: 200,
    imageHint: "iphones in evidence bag",
  },
  {
    id: "spp-26-441",
    lane: "midwest",
    venue: "stpaul-pd",
    venueLabel: "St. Paul PD",
    lotNo: "441",
    title: "Men's 'Rolex' Submariner — no papers, heavy",
    category: "watch",
    city: "Saint Paul",
    state: "MN",
    miles: 12,
    endsAt: T("2026-09-04"),
    hammer: 350,
    bidders: 9,
    titleStatus: "none",
    flags: ["auth-risk", "no-papers"],
    notes: "Evidence photo is a phone pic under fluorescent. Don't bid a story.",
    comps: [
      { label: "Genuine 16610 street", price: 8200 },
      { label: "DHGate homage", price: 80 },
    ],
    retail: 80,
    imageHint: "watch on blotter",
  },
  {
    id: "blm-26-77",
    lane: "midwest",
    venue: "bloomington-pd",
    venueLabel: "Bloomington PD",
    lotNo: "77",
    title: "Specialized Stumpjumper carbon — no serial on file",
    category: "bike",
    city: "Bloomington",
    state: "MN",
    miles: 14,
    endsAt: T("2026-09-05"),
    hammer: 220,
    bidders: 4,
    titleStatus: "none",
    flags: ["no-title", "serial-missing"],
    notes: "Nice frame. Serial ground. Pawn shops in the Cities will bounce it.",
    comps: [{ label: "Stumpjumper Alloy used", price: 1400 }],
    retail: 400,
    imageHint: "mountain bike",
  },
  {
    id: "gd-mpls-3301",
    lane: "midwest",
    venue: "govdeals",
    venueLabel: "GovDeals · City of Minneapolis",
    lotNo: "3301",
    title: "2018 Chevy Tahoe SSV — 121k, side-wipe, clean title",
    category: "vehicle",
    city: "Minneapolis",
    state: "MN",
    miles: 6,
    endsAt: T("2026-09-08"),
    hammer: 4100,
    reserve: 3500,
    bidders: 6,
    titleStatus: "clean",
    flags: ["needs-work", "body"],
    notes: "Passenger quarter crushed. Drives. Sister-unit body quote was $2,100.",
    comps: [
      { label: "2018 SSV 110k wholesale", price: 9800 },
      { label: "Retail private 2018 130k", price: 12500 },
    ],
    retail: 10800,
    imageHint: "black tahoe police",
  },
  {
    id: "mndot-884",
    lane: "midwest",
    venue: "mndot",
    venueLabel: "GovDeals · MnDOT",
    lotNo: "884",
    title: "2014 Freightliner dump — 210k, plow package, runs",
    category: "equipment",
    city: "Roseville",
    state: "MN",
    miles: 11,
    endsAt: T("2026-09-10"),
    hammer: 9800,
    bidders: 3,
    titleStatus: "clean",
    flags: ["heavy", "needs-cdl-driver"],
    notes: "Yard will not load. You bring a CDL and a lowboy.",
    comps: [
      { label: "2014 dump midwest auction", price: 22000 },
      { label: "Dealer retail similar", price: 28000 },
    ],
    retail: 21000,
    imageHint: "orange dump truck plow",
  },
  {
    id: "dak-26-119",
    lane: "midwest",
    venue: "dakota-municibid",
    venueLabel: "Dakota Municibid",
    lotNo: "119",
    title: "Toro Power Max 826 snowblower lot (6) — mixed hours",
    category: "seasonal",
    city: "Hastings",
    state: "MN",
    miles: 28,
    endsAt: T("2026-09-06"),
    hammer: 410,
    bidders: 5,
    titleStatus: "none",
    flags: ["seasonal-hold"],
    notes: "August is the buy. November is the sale.",
    comps: [{ label: "826 October FB", price: 380 }],
    retail: 2100,
    imageHint: "red snowblowers",
  },
  {
    id: "anoka-55",
    lane: "midwest",
    venue: "anoka-surplus",
    venueLabel: "Anoka County Surplus",
    lotNo: "55",
    title: "Milwaukee packout + M18 kit — 4 batteries, charger, 9 tools",
    category: "tools",
    city: "Anoka",
    state: "MN",
    miles: 27,
    endsAt: T("2026-09-03"),
    hammer: 240,
    bidders: 8,
    titleStatus: "none",
    flags: ["complete"],
    notes: "Batteries hold a charge per the yard note. Saturday morning Facebook lot.",
    comps: [
      { label: "M18 combo used", price: 520 },
      { label: "Packout rolling", price: 180 },
    ],
    retail: 680,
    imageHint: "milwaukee tool kit",
  },
  {
    id: "hcs-26-1902",
    lane: "midwest",
    venue: "hennepin-sheriff",
    venueLabel: "Hennepin Sheriff",
    lotNo: "1902",
    title: "14k yellow gold chain + herringbone — 18.2 dwt weighed",
    category: "jewelry",
    city: "Minneapolis",
    state: "MN",
    miles: 8,
    endsAt: T("2026-09-03"),
    hammer: 620,
    bidders: 6,
    titleStatus: "none",
    flags: ["weighed"],
    notes: "Sheriff weighed it. Melt is the floor. Retail chain buyers pay a premium if clasps are sound.",
    comps: [
      { label: "Melt 18.2 dwt 14k", price: 510 },
      { label: "Retail herringbone 18dwt", price: 980 },
    ],
    retail: 890,
    imageHint: "gold chain",
  },
  {
    id: "gd-stp-212",
    lane: "midwest",
    venue: "govdeals",
    venueLabel: "GovDeals · St. Paul Public Works",
    lotNo: "212",
    title: "Honda EU2200i inverter generator — 412 hours",
    category: "equipment",
    city: "Saint Paul",
    state: "MN",
    miles: 11,
    endsAt: T("2026-09-07"),
    hammer: 310,
    bidders: 4,
    titleStatus: "none",
    flags: ["tested"],
    notes: "Fired in the yard video. These still clear $550–650 if the inverter is quiet.",
    comps: [{ label: "EU2200i used Cities", price: 600 }],
    retail: 620,
    imageHint: "honda generator",
  },
  {
    id: "mpd-26-1004",
    lane: "midwest",
    venue: "minneapolis-pd",
    venueLabel: "Minneapolis PD",
    lotNo: "1004",
    title: "2013 Honda CBR 600RR — no title, key present",
    category: "powersport",
    city: "Minneapolis",
    state: "MN",
    miles: 4,
    endsAt: T("2026-09-02"),
    hammer: 900,
    bidders: 10,
    titleStatus: "none",
    flags: ["no-title"],
    notes: "Pretty bike. Paper is a property receipt. DVS bonded title is a six-month science project.",
    comps: [{ label: "2013 CBR titled 18k miles", price: 4200 }],
    retail: 900,
    imageHint: "red sportbike",
  },
  {
    id: "dak-26-140",
    lane: "midwest",
    venue: "dakota-municibid",
    venueLabel: "Dakota Municibid",
    lotNo: "140",
    title: "2019 Ford F-150 XLT 4x4 — 96k, city parks, clean",
    category: "vehicle",
    city: "Apple Valley",
    state: "MN",
    miles: 22,
    endsAt: T("2026-09-09"),
    hammer: 11200,
    reserve: 10800,
    bidders: 5,
    titleStatus: "clean",
    flags: ["fleet-service"],
    notes: "Parks unit. Bed liner, hitch, one owner city.",
    comps: [
      { label: "2019 XLT 4x4 90k private", price: 19800 },
      { label: "Dealer trade", price: 17200 },
    ],
    retail: 18400,
    imageHint: "white f150",
  },
  {
    id: "anoka-61",
    lane: "midwest",
    venue: "anoka-surplus",
    venueLabel: "Anoka County Surplus",
    lotNo: "61",
    title: "Dell Latitude lot (24) — mixed i5, no chargers, BIOS locked on 6",
    category: "electronics",
    city: "Anoka",
    state: "MN",
    miles: 27,
    endsAt: T("2026-09-03"),
    hammer: 160,
    bidders: 3,
    titleStatus: "none",
    flags: ["partial-lock"],
    notes: "Eighteen will image. Six are supervisor-password bricks.",
    comps: [{ label: "Latitude i5 bulk", price: 55 }],
    retail: 990,
    imageHint: "laptops stacked",
  },
  {
    id: "blm-26-81",
    lane: "midwest",
    venue: "bloomington-pd",
    venueLabel: "Bloomington PD",
    lotNo: "81",
    title: "DeWalt 20V compact combo + two 5Ah — tested",
    category: "tools",
    city: "Bloomington",
    state: "MN",
    miles: 14,
    endsAt: T("2026-09-05"),
    hammer: 95,
    bidders: 6,
    titleStatus: "none",
    flags: ["tested"],
    notes: "Small lot, clean tools. This is how you keep the lights on between vehicles.",
    comps: [{ label: "DCK slimmer combo", price: 240 }],
    retail: 230,
    imageHint: "dewalt drill kit",
  },
  {
    id: "hcs-26-1910",
    lane: "midwest",
    venue: "hennepin-sheriff",
    venueLabel: "Hennepin Sheriff",
    lotNo: "1910",
    title: "2011 Chevy Impala 9C3 — 189k, burns a little, clean title",
    category: "vehicle",
    city: "Minneapolis",
    state: "MN",
    miles: 8,
    endsAt: T("2026-09-03"),
    hammer: 450,
    bidders: 2,
    titleStatus: "clean",
    flags: ["needs-work", "smoke"],
    notes: "Puff on startup. Wholesale to the Lake Street lot, don't retail it.",
    comps: [
      { label: "2011 9C3 running", price: 1600 },
      { label: "Wholesale beaters", price: 900 },
    ],
    retail: 1400,
    imageHint: "white impala police",
  },
  {
    id: "mndot-901",
    lane: "midwest",
    venue: "mndot",
    venueLabel: "GovDeals · MnDOT",
    lotNo: "901",
    title: "Wacker Neuson jump rammer — compression good",
    category: "equipment",
    city: "Golden Valley",
    state: "MN",
    miles: 9,
    endsAt: T("2026-09-11"),
    hammer: 380,
    bidders: 2,
    titleStatus: "none",
    flags: ["tested"],
    notes: "Contractors pay for these in April. Hold or flip to a Brooklyn Park site this week.",
    comps: [{ label: "Jumping jack used", price: 1100 }],
    retail: 980,
    imageHint: "construction rammer",
  },
];

export function scoredMidwest(): ScoredLot[] {
  return MIDWEST.map((lot) => ({ ...lot, score: scoreLot(lot) })).sort(
    (a, b) => b.score.yield - a.score.yield,
  );
}
